<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>Starter.SearchEngine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.1" />
        <PackageReference Include="FluentIcons.Common" Version="1.1.302" />
        <PackageReference Include="R3" Version="1.3.0" />
    </ItemGroup>

</Project>
