<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net9.0-windows10.0.19041.0</TargetFrameworks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starter.SearchEngineBase\Starter.SearchEngineBase.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Types.fs" />
        <Compile Include="Loaders\IconHelper.fs" Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'" />
        <Compile Include="Loaders\UwpLoader.fs" Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'" />
        <Compile Include="Loaders\ExecutableFilesLoader.fs" Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'" />
        <Compile Include="Library.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.18.0" />
        <PackageReference Include="Vanara.Windows.Shell" Version="4.2.0" />
        <PackageReference Update="FSharp.Core" Version="9.0.303" />
    </ItemGroup>

</Project>
