<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net9.0-windows10.0.19041.0</TargetFrameworks>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableDynamicLoading>true</EnableDynamicLoading>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starter.SearchEngineBase\Starter.SearchEngineBase.csproj">
            <Private>false</Private>
            <ExcludeAssets>runtime</ExcludeAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Types.fs" />
        <Compile Include="Logger.fs" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0-windows10.0.19041.0'">
        <Compile Include="Windows\IconHelper.fs" />
        <Compile Include="Windows\UwpLoader.fs" />
        <Compile Include="Windows\ExecutableFilesLoader.fs" />
        <Compile Include="Windows\Library.fs" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' != 'net9.0-windows10.0.19041.0'">
        <Compile Include="Linux\Types.fs" />
        <Compile Include="Linux\IconLoader.fs" />
        <Compile Include="Linux\XDGDesktopFileParser.fs" />
        <Compile Include="Linux\AppsLoader.fs" />
        <Compile Include="Linux\Library.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.18.0" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.0.4" />
        <PackageReference Include="Vanara.Windows.Shell" Version="4.2.0" />
        <PackageReference Update="FSharp.Core" Version="9.0.303" />
    </ItemGroup>

</Project>
