<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows10.0.19041.0</TargetFrameworks>
        <ParallelCompilation>true</ParallelCompilation>
        <Deterministic>false</Deterministic>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <Nullable>enable</Nullable>
        <IsPlugin>true</IsPlugin>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Types.fs" />
        <Compile Include="Logger.fs" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows10.0.19041.0'">
        <Compile Include="Windows\Uwp\Types.fs" />
        <Compile Include="Windows\Uwp\AppxManifest.fs" />
        <Compile Include="Windows\Uwp\UwpLoader.fs" />

        <Compile Include="Windows\Exe\IconHelper.fs" />
        <Compile Include="Windows\Exe\ExeLoader.fs" />

        <Compile Include="Windows\Config.fs" />
        <Compile Include="Windows\Settings.axaml.fs" />
        <Compile Include="Windows\Library.fs" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentAvaloniaUI" Version="3.0.1" />
        <PackageReference Include="Vanara.Windows.Shell" Version="5.0.5" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' != 'net10.0-windows10.0.19041.0'">
        <AvaloniaXaml Remove="Windows\Settings.axaml" />
        <Compile Include="Linux\Types.fs" />
        <Compile Include="Linux\Helpers.fs" />

        <Compile Include="Linux\XDGDesktopFileParser.fs" />
        <Compile Include="Linux\Theme\Types.fs" />
        <Compile Include="Linux\Theme\IconThemeParser.fs" />
        <Compile Include="Linux\Theme\IconLookup.fs" />
        <Compile Include="Linux\Theme\ThemeDetection.fs" />
        <Compile Include="Linux\Theme\IconLoader.fs" />

        <Compile Include="Linux\AppsLoader.fs" />
        <Compile Include="Linux\Library.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StarterApp.SearchEngineBase" Version="0.2.0">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="FsToolkit.ErrorHandling" Version="5.1.0" />
    </ItemGroup>

</Project>
