<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Fonts\" />
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <!-- Platform interop -->
        <Compile Include="Features\PlatformInterop\PlatformInterop.fs" />
        <Compile Include="Features\PlatformInterop\Windows.fs" />
        <Compile Include="Features\PlatformInterop\Linux.fs" />
        <Compile Include="Features\PlatformInterop\PlatformInteropFactory.fs" />
        
        <!-- Features -->
        <Compile Include="Features\Configuration\Config.fs" />
        <Compile Include="Features\SearchEngineLoading.fs" />
        <Compile Include="Features\ScoresSaver.fs" />
        
        <!-- View / View Models -->
        <Compile Include="ViewModels\ViewModelBase.fs" />
        <Compile Include="ViewModels\SearchResultViewModel.fs" />
        <Compile Include="ViewModels\SettingsViewModel.fs" />

        <!-- Views -->
        <Compile Include="Views\SearchResult.axaml.fs">
            <DependentUpon>SearchResult.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Include="Views\Settings.axaml.fs">
            <DependentUpon>Settings.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>

        <!-- Internal search engines -->
        <Compile Include="Features\InternalSearchEngines\SettingsSearchEngine.fs" />

        <!-- Main view/view model -->
        <Compile Include="ViewModels\MainWindowViewModel.fs" />
        <Compile Include="Views\MainWindow.axaml.fs">
          <DependentUpon>MainWindow.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Include="ViewLocator.fs" />
        <Compile Include="App.axaml.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.5" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.5">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAvaloniaUI" Version="2.3.0" />
        <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="1.1.292" />
        <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.18.0" />
        <PackageReference Include="MemoryPack" Version="1.21.4" />
        <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
        <PackageReference Include="System.Reactive" Version="6.0.1" />
        <PackageReference Include="Thoth.Json.Net" Version="12.0.0" />
        <PackageReference Include="Vanara.PInvoke.Shell32" Version="4.1.1" />
        <PackageReference Include="Vanara.PInvoke.User32" Version="4.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="Plugins\Starter.SearchEngineBase\Starter.SearchEngineBase.csproj" />
    </ItemGroup>
</Project>
