<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Shared</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="IconHelper.fs" />
        <Compile Include="ContextMenu.fs" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="StarterApp.SearchEngineBase" Version="0.3.0">
            <ExcludeAssets>runtime;native</ExcludeAssets>
        </PackageReference>
        <PackageReference Include="Vanara.Windows.Shell" Version="5.0.5" />
        <PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0" />
    </ItemGroup>

</Project>
