<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ParallelCompilation>true</ParallelCompilation>
        <Deterministic>false</Deterministic>
        <Nullable>enable</Nullable>
        <RootNamespace>Starter</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Constants.fs" />
        <Compile Include="Helpers.fs" />
        <Compile Include="Logging.fs" />
        <Compile Include="Config.fs" />

        <!-- Platform interop -->
        <Compile Include="PlatformInterop\PlatformInterop.fs" />
        <Compile Include="PlatformInterop\Linux\Common.fs" />
        <Compile Include="PlatformInterop\Linux\Gnome.fs" />
        <Compile Include="PlatformInterop\Linux\KeyboardShortcut.fs" />
        <Compile Include="PlatformInterop\LinuxPlatformInterop.fs" />
        <Compile Include="PlatformInterop\WindowsPlatformInterop.fs" />

        <Compile Include="SearchEngineLoading.fs" />
        <Compile Include="ResultScores.fs" />
        <Compile Include="ActivatorStore.fs" />
        <Compile Include="CustomCollections.fs" />
        <Compile Include="SearchResultData.fs" />
        <Compile Include="SearchResultStore.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StarterApp.SearchEngineBase" Version="0.2.0" />
        <PackageReference Include="Fusil" Version="1.0.8" />
        <PackageReference Include="MemoryPack" Version="1.21.4" />
        <PackageReference Include="FsToolkit.ErrorHandling" Version="5.1.0" />
        <PackageReference Include="ObservableCollections" Version="3.3.4" />
        <PackageReference Include="R3" Version="1.3.1" />
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" Condition="'$(Configuration)' == 'Debug' Or $(DefineConstants.Contains(DEBUG_LOGS))" />
        <PackageReference Include="System.Reactive" Version="7.0.0-preview.1" />
        <PackageReference Include="Thoth.Json.Net" Version="12.0.0" />
        <PackageReference Include="Tmds.DBus" Version="0.94.1" />
        <PackageReference Include="Vanara.PInvoke.Shell32" Version="5.0.5" />
        <PackageReference Include="Vanara.PInvoke.User32" Version="5.0.5" />
        <PackageReference Include="Vanara.Windows.Shell" Version="5.0.5" />
    </ItemGroup>

    <!-- Avalonia related packages -->
    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
        <PackageReference Include="Avalonia.Win32" Version="12.0.4" />
        <PackageReference Include="FluentAvaloniaUI" Version="3.0.0-preview2" />
        <PackageReference Include="R3Extensions.Avalonia" Version="1.3.1" />
    </ItemGroup>
</Project>
