<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <GenerateProgramFile>false</GenerateProgramFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Common.fs" />
        <Compile Include="Tests\HotkeyRegistration.fs" />
        <Compile Include="Tests\SearchResultFiltering.fs" />
        <Compile Include="Tests\SearchEngineActivator.fs" />
        <Compile Include="Tests\ResultsOrdering.fs" />
        <Compile Include="Tests\SearchEngineIntegration.fs" />
        <Compile Include="Tests\KeyboardNavigation.fs" />
        <Compile Include="TestAppBuilder.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless.NUnit" Version="12.0.3" />
        <PackageReference Include="coverlet.collector" Version="10.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageReference Include="NUnit" Version="4.6.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.13.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Starter\Starter.csproj" />
    </ItemGroup>

</Project>
