module Native.Windows.Api

open System.Runtime.InteropServices
open System.Runtime.Versioning

type WParam = unativeint
type LParam = nativeint
type LResult = nativeint

type HWND = System.IntPtr

type HOT_KEY_MODIFIERS =
    /// Either ALT key must be held down.
    | MOD_ALT = 0x0001u
    /// Either CTRL key must be held down.
    | MOD_CONTROL = 0x0002u
    /// Changes the hotkey behavior so that the keyboard auto-repeat does not yield multiple hotkey notifications.
    | MOD_NOREPEAT = 0x4000u
    /// Either SHIFT key must be held down.
    | MOD_SHIFT = 0x0004u
    /// Either WINDOWS key must be held down. These keys are labeled with the Windows logo. Keyboard shortcuts that involve the WINDOWS key are reserved for use by the operating system.
    | MOD_WIN = 0x0008u

type WINDOW_MESSAGE =
    | WM_HOTKEY = 0x0312u

[<RequireQualifiedAccess>]
module User32 =
    /// <summary>Defines a system-wide hot key.</summary>
    /// <param name="hWnd">
    /// <para>Type: <b>HWND</b> A handle to the window that will receive <a href="https://docs.microsoft.com/windows/desktop/inputdev/wm-hotkey">WM_HOTKEY</a> messages generated by the hot key. If this parameter is <b>NULL</b>, <b>WM_HOTKEY</b> messages are posted to the message queue of the calling thread and must be processed in the message loop.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-registerhotkey#parameters">Read more on docs.microsoft.com</see>.</para>
    /// </param>
    /// <param name="id">
    /// <para>Type: <b>int</b> The identifier of the hot key.  If the <i>hWnd</i> parameter is NULL, then the hot key is associated with the current thread rather than with a particular window. If a hot key already exists with the same <i>hWnd</i> and <i>id</i> parameters, see Remarks for the action taken.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-registerhotkey#parameters">Read more on docs.microsoft.com</see>.</para>
    /// </param>
    /// <param name="fsModifiers">
    /// <para>Type: <b>UINT</b> The keys that must be pressed in combination with the key specified by the</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-registerhotkey#parameters">Read more on docs.microsoft.com</see>.</para>
    /// </param>
    /// <param name="vk">
    /// <para>Type: <b>UINT</b> The virtual-key code of the hot key. See <a href="https://docs.microsoft.com/windows/desktop/inputdev/virtual-key-codes">Virtual Key Codes</a>.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-registerhotkey#parameters">Read more on docs.microsoft.com</see>.</para>
    /// </param>
    /// <returns>
    /// <para>Type: <b>BOOL</b> If the function succeeds, the return value is nonzero. If the function fails, the return value is zero. To get extended error information, call <a href="https://docs.microsoft.com/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror">GetLastError</a>.</para>
    /// </returns>
    /// <remarks>
    /// <para>When a key is pressed, the system looks for a match against all hot keys. Upon finding a match, the system posts the <a href="https://docs.microsoft.com/windows/desktop/inputdev/wm-hotkey">WM_HOTKEY</a> message to the message queue of the window with which the hot key is associated. If the hot key is not associated with a window, then the <b>WM_HOTKEY</b> message is posted to the thread associated with the hot key. This function cannot associate a hot key with a window created by another thread. <b>RegisterHotKey</b> fails if the keystrokes specified for the hot key have already been registered by another hot key. If a hot key already exists with the same <i>hWnd</i> and <i>id</i> parameters, it is maintained along with the new hot key.  The application must explicitly call <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-unregisterhotkey">UnregisterHotKey</a> to unregister the old hot key. <b>Windows Server 2003:  </b>If a hot key already exists with the same <i>hWnd</i> and <i>id</i> parameters, it is replaced by the new hot key. The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident. An application must specify an id value in the range 0x0000 through 0xBFFF. A shared DLL must specify a value in the range 0xC000 through 0xFFFF (the range returned by the <a href="https://docs.microsoft.com/windows/desktop/api/winbase/nf-winbase-globaladdatoma">GlobalAddAtom</a> function). To avoid conflicts with hot-key identifiers defined by other shared DLLs, a DLL should use the <b>GlobalAddAtom</b> function to obtain the hot-key identifier.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-registerhotkey#">Read more on docs.microsoft.com</see>.</para>
    /// </remarks>
    [<DllImport("USER32.dll", ExactSpelling = true, SetLastError = true)>]
    [<DefaultDllImportSearchPaths(DllImportSearchPath.System32)>]
    [<SupportedOSPlatform("windows6.0.6000")>]
    extern bool RegisterHotKey(HWND hWnd, int id, HOT_KEY_MODIFIERS fsModifiers, uint vk);

    /// <summary>Frees a hot key previously registered by the calling thread.</summary>
    /// <param name="hWnd">
    /// <para>Type: <b>HWND</b> A handle to the window associated with the hot key to be freed. This parameter should be <b>NULL</b> if the hot key is not associated with a window.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-unregisterhotkey#parameters">Read more on docs.microsoft.com</see>.</para>
    /// </param>
    /// <param name="id">
    /// <para>Type: <b>int</b> The identifier of the hot key to be freed.</para>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-unregisterhotkey#parameters">Read more on docs.microsoft.com</see>.</para>
    /// </param>
    /// <returns>
    /// <para>Type: <b>BOOL</b> If the function succeeds, the return value is nonzero. If the function fails, the return value is zero. To get extended error information, call <a href="https://docs.microsoft.com/windows/desktop/api/errhandlingapi/nf-errhandlingapi-getlasterror">GetLastError</a>.</para>
    /// </returns>
    /// <remarks>
    /// <para><see href="https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-unregisterhotkey">Learn more about this API from docs.microsoft.com</see>.</para>
    /// </remarks>
    [<DllImport("USER32.dll", ExactSpelling = true, SetLastError = true)>]
    [<DefaultDllImportSearchPaths(DllImportSearchPath.System32)>]
    [<SupportedOSPlatform("windows5.0")>]
    extern bool UnregisterHotKey(HWND hWnd, int id);