<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType Condition="'$(Configuration)' == 'Debug' Or $(DefineConstants.Contains(DEBUG_LOGS))">Exe</OutputType>
        <OutputType Condition="'$(Configuration)' != 'Debug' And !$(DefineConstants.Contains(DEBUG_LOGS))">WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PublishSelfContained>true</PublishSelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="CommunityToolkit.Mvvm.ComponentModel" />
        <Using Include="CommunityToolkit.Mvvm.Input" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starter.Model\Starter.Model.fsproj" />
        <InternalsVisibleTo Include="Starter.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.4" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
        <!-- Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration. -->
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.2">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentAvaloniaUI" Version="3.0.0-preview2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
        <PackageReference Include="R3Extensions.Avalonia" Version="1.3.1" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.11" />
    </ItemGroup>
</Project>
