<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType Condition="'$(Configuration)' == 'Debug' Or $(DefineConstants.Contains(DEBUG_LOGS))">Exe</OutputType>
        <OutputType Condition="'$(Configuration)' != 'Debug' And !$(DefineConstants.Contains(DEBUG_LOGS))">WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ParallelCompilation>true</ParallelCompilation>
        <Deterministic>false</Deterministic>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Starter.SearchEngineBase\Starter.SearchEngineBase.csproj" />
    </ItemGroup>

    <!-- Features -->
    <ItemGroup>
        <Compile Include="Features\Constants.fs" />
        <Compile Include="Features\Helpers.fs" />

        <!-- Logging -->
        <Compile Include="Features\Logging\Logging.fs" />
        <Compile Include="Features\Logging\LogsView.axaml.fs" />

        <!-- Config -->
        <Compile Include="Features\Configuration\Config.fs" />
        <Compile Include="Features\Configuration\ActivatorStore.fs" />

        <!-- Platform interop -->
        <Compile Include="Features\PlatformInterop\PlatformInterop.fs" />
        <Compile Include="Features\PlatformInterop\Linux\Common.fs" />
        <Compile Include="Features\PlatformInterop\Linux\Gnome.fs" />
        <Compile Include="Features\PlatformInterop\Linux\KeyboardShortcut.fs" />
        <Compile Include="Features\PlatformInterop\LinuxPlatformInterop.fs" />
        <Compile Include="Features\PlatformInterop\WindowsPlatformInterop.fs" />
        <Compile Include="Features\PlatformInterop\PlatformInteropFactory.fs" />

        <!-- Custom Controls -->
        <Compile Include="Controls\AccentuatedTextBlock.fs" />
        <Compile Include="Controls\StarterIcon.fs" />
        <Compile Include="Controls\TranslucentWindow.fs" />

        <!-- Internal search engines -->
        <Compile Include="Features\InternalSearchEngines\Settings\ViewModels\ActivatorPrefixesViewModel.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\ViewModels\KeyboardShortcutInputViewModel.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\ViewModels\SettingsViewModel.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\Views\ActivatorPrefixesView.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\Views\KeyboardShortcutInput.axaml.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\Views\Settings.axaml.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\ViewModels\SettingsWindowViewModel.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\Views\SettingsWindow.axaml.fs" />
        <Compile Include="Features\InternalSearchEngines\Settings\SettingsSearchEngine.fs" />

        <!-- Others -->
        <Compile Include="Features\SearchEngineLoading.fs" />
        <Compile Include="Features\ResultScores.fs" />
        <Compile Include="Features\ObservableList.fs" />
    </ItemGroup>

    <ItemGroup>
        <!-- View models -->
        <Compile Include="ViewModels\ViewModelBase.fs" />
        <Compile Include="ViewModels\SearchResultViewModel.fs" />
        <Compile Include="ViewModels\MainWindowViewModel.fs" />

        <!-- Views -->
        <Compile Include="Views\SearchResult.axaml.fs" />
        <Compile Include="Views\SearchEnginePill.axaml.fs" />
        <Compile Include="Views\MainWindow.axaml.fs" />

        <!-- Entry point -->
        <Compile Include="ViewLocator.fs" />
        <Compile Include="App.axaml.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Fusil" Version="1.0.7" />
        <PackageReference Include="MemoryPack" Version="1.21.4" />
        <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.18.0" />
        <PackageReference Include="R3" Version="1.3.0" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" Condition="'$(Configuration)' == 'Debug' Or $(DefineConstants.Contains(DEBUG_LOGS))" />
        <!--<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.0" />-->
        <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
        <PackageReference Include="Thoth.Json.Net" Version="12.0.0" />
        <PackageReference Include="Tmds.DBus" Version="0.22.0" />
        <PackageReference Include="Vanara.PInvoke.Shell32" Version="4.2.1" />
        <PackageReference Include="Vanara.PInvoke.User32" Version="4.2.1" />
        <PackageReference Include="Vanara.Windows.Shell" Version="4.2.1" />
    </ItemGroup>

    <!-- Avalonia related packages -->
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.10" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.8" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAvaloniaUI" Version="2.4.1" />
        <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="2.0.316.1" />
        <PackageReference Include="R3Extensions.Avalonia" Version="1.3.0" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="11.3.6.2" />
    </ItemGroup>
</Project>
