name: Build Installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build the Windows installer
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [win-x64, win-x86, win-arm64]
    steps:
      - uses: actions/checkout@v4

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build Starter
        run: dotnet publish --configuration Release --self-contained --runtime ${{ matrix.rid }} -o ./build/${{ matrix.rid }}
        working-directory: src/Starter

      - name: Compile installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: src/Starter.Installer/starter-setup.iss
          options: /O+ /F"Starter-setup-${{ matrix.rid }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows installer
          path: src/Starter.Installer/Starter-setup.exe
